### ISSUE TITLE
Setting `prerelease` to `''` and `doNotFailIfNotFound` to `true` still fails with an `HttpRequest: Not Found` error when there are no releases

### ISSUE THREAD

**Issue by just-ero** [cardinalby/git-get-release-action#13]
I have the following step in my workflow:

```yml
- name: Fetch previous release
  id: previous-release
  uses: cardinalby/git-get-release-action@v1
  env:
    GITHUB_TOKEN: ${{ github.token }}
  with:
    latest: true
    prerelease: ${{ !inputs.prerelease && 'false' || '' }}
    doNotFailIfNotFound: true
```

The condition here may be a bit confusing, let me explain:
* when the new release is a pre-release (set via `inputs.prerelease`), then search for the latest release in ALL releases (pre-release or not),
* when the new release is not a pre-release, then *only* search for other non-pre-releases.

When there has not been any release on the repository ever, but the first release is a pre-release (setting `prerelease: ''` in the step), then the step still fails with an `HttpRequest: Not Found` error, despite `doNotFailIfNotFound` being set to `true`.
