### ISSUE TITLE
Error: Not Found on 1.1 (works on 1.0)

### ISSUE THREAD

**Issue by SudoPlz** [cardinalby/git-get-release-action#5]
Hey there,

not sure why, but when I run the following action in 1.1:

```
- name: Fetch release by commit sha
        uses: cardinalby/git-get-release-action@v1.0
        if: steps.releaseFilter.outputs.OUTPUT == 0
        id: get_release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          commitSha: ${{ github.sha }}
```

I get a weird `Error: Not Found` error.

![terr](https://user-images.githubusercontent.com/3070948/117208185-8256f480-adfd-11eb-9e12-2ceab3e9fd5c.png)

I know the commit sha is correct because:

1) the get releases api returns it when I GET /releases
```
{
  "url": "...",
  "assets_url": "...",
  "upload_url": "...",
  "html_url": "...",
  "id": "...",
  "author": "...",
  "node_id": "...",
  "tag_name": "1.1.8",
  "target_commitish": "f769ba9cb06907baafcbfe96634f5470746188b7",
  "name": "Native release 1.1.8",
  "draft": false,
  "prerelease": false,
  "created_at": "2021-05-05T19:03:49Z",
  "published_at": "2021-05-05T20:08:20Z",
  ...
}
```
and here's what the release looks like in github:

![release2](https://user-images.githubusercontent.com/3070948/117210641-a49e4180-ae00-11eb-9a14-c4a5abd02883.png)

Note the sha `f769ba9cb06907baafcbfe96634f5470746188b7` being right?

(The release is part if the repo that runs github actions in case you were wondering if I'm doing anything stupid like running actions from a different repo)

Here's the [first chunk of my yml](https://gist.github.com/SudoPlz/3e1e097a251b3b3503ddecd94b827186) file (that fails)

**I confirm this works if I revert back to version 1**

Something is fishy here..

Thanks

p.s Everything works fine when I use a release name
